package Vista;

//import Formatos.ProductoControl;
//import Entidades.Categoria;
//import Entidades.Proveedor;
//import javax.swing.DefaultComboBoxModel;
//import javax.swing.JOptionPane;
//import javax.swing.table.TableRowSorter;

public class FrmProducto extends javax.swing.JFrame {

//    private final ProductoControl CONTROL;
//    private String accion;
//    String nombreAnterior;

    public FrmProducto() {
        initComponents();

//        this.CONTROL = new ProductoControl();
//        accion = "guardar";
//        tabGeneral.setEnabledAt(1, false);
//        listar();
//        cargarCategoria();
//        cargarProveedor();
    }

//    private void cargarCategoria() {
//        DefaultComboBoxModel item = CONTROL.seleccionarCategoria();
//        cboCategoria.setModel(item);
//    }
//
//    private void cargarProveedor() {
//        DefaultComboBoxModel item = CONTROL.seleccionarProveedor();
//        cboProveedor.setModel(item);
//    }
//
//    private void listar() {
//        tabla.setModel(CONTROL.listar());
//        TableRowSorter orden = new TableRowSorter(tabla.getModel());
//        tabla.setRowSorter(orden);
//    }
//
//    private void limpiar() {
//        txtId.setText("");
//        txtNombre.setText("");
//        txtPrecio.setText("");
//        txtStock.setText("");
//        accion = "guardar";
//    }

//    private void mensajeError(String mensaje) {
//        JOptionPane.showMessageDialog(null, mensaje, "Sistema", JOptionPane.ERROR_MESSAGE);
//    }
//
//    private void mensajeOK(String mensaje) {
//        JOptionPane.showMessageDialog(null, mensaje, "Sistema", JOptionPane.INFORMATION_MESSAGE);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabGeneral = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cboCategoria = new javax.swing.JComboBox<>();
        cboProveedor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, 700, 300));

        btnNuevo.setBackground(new java.awt.Color(102, 204, 255));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 52, 120, 30));

        btnEditar.setBackground(new java.awt.Color(153, 153, 255));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 120, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel7.setText("Listado de Productos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 250, 30));

        tabGeneral.addTab("Listado", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 200, 30));

        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 30));

        jLabel1.setText("ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel3.setText("Precio:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel4.setText("Proveedor:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 20));

        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 200, 30));

        txtStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 200, 30));

        btnGuardar.setBackground(new java.awt.Color(102, 153, 255));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 140, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 140, 40));

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 200, 30));

        cboProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 200, 30));

        jLabel5.setText("Stock:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel6.setText("Categoria:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel8.setText("Registro de Productos");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 250, 30));

        tabGeneral.addTab("Mantenimiento", jPanel2);

        getContentPane().add(tabGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 720, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
//        if (tabla.getSelectedRowCount() == 1) {
//            String ruc = String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 0));
//            String nombre = String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 1));
//            String precio = String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 2));
//            String stock = String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 3));
//            String idCategoria = String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 4));
//            String nombreCategoria = String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 5));
//            String idProveedor = String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 6));
//            String nombreProveedor = String.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 7));
//            nombreAnterior = nombre;
//
//            txtId.setText(ruc);
//            txtNombre.setText(nombre);
//            txtPrecio.setText(precio);
//            txtStock.setText(stock);
//
//            txtId.setEditable(false);
//
//            cboCategoria.setSelectedItem(new Categoria(Integer.parseInt(idCategoria), nombreCategoria));
//            cboProveedor.setSelectedItem(new Proveedor(Integer.parseInt(idProveedor), nombreProveedor));
//
//            tabGeneral.setEnabledAt(0, false);
//            tabGeneral.setEnabledAt(1, true);
//            tabGeneral.setSelectedIndex(1);
//            this.accion = "editar";
//            btnGuardar.setText("Editar");
//        } else {
//            this.mensajeError("Seleccione un registro a Editar");
//        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
//        tabGeneral.setEnabledAt(0, false);
//        tabGeneral.setEnabledAt(1, true);
//        tabGeneral.setSelectedIndex(1);
//        this.accion = "guardar";
//        btnGuardar.setText("Guardar");
//        txtId.setEditable(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
//        if (txtId.getText().trim().length() == 0 || txtId.getText().trim().length() > 11) {
//            this.mensajeError("Debes ingresar un ID y no debe ser mayor a 11 caracteres, es obligatorio");
//            txtId.requestFocus();
//            return;
//        }
//        if (txtNombre.getText().trim().length() == 0 || txtNombre.getText().trim().length() > 45) {
//            this.mensajeError("Debes ingresar un nombre y no debe ser mayor a 45 caracteres, es obligatorio");
//            txtNombre.requestFocus();
//            return;
//        }
//
//        if (txtPrecio.getText().trim().length() == 0 || txtPrecio.getText().trim().length() > 10) {
//            this.mensajeError("Debes ingresar un precio y no debe ser mayor a 10 caracteres, es obligatorio");
//            txtPrecio.requestFocus();
//            return;
//        }
//        if (txtStock.getText().trim().length() == 0 || txtStock.getText().trim().length() > 11) {
//            this.mensajeError("Debes ingresar un stock y no debe ser mayor a 11 caracteres, es obligatorio");
//            txtStock.requestFocus();
//            return;
//        }
//        if (cboCategoria.getItemCount() == 0) {
//            this.mensajeError("Debe seleccionar una categoria");
//            cboCategoria.requestFocus();
//            return;
//        }
//        if (cboProveedor.getItemCount() == 0) {
//            this.mensajeError("Debe seleccionar un Proveedor");
//            cboProveedor.requestFocus();
//            return;
//        }
//
//        Categoria cat = (Categoria) cboCategoria.getSelectedItem();
//        Proveedor prov = (Proveedor) cboProveedor.getSelectedItem();
//
//        String resp;
//        if (accion.equals("editar")) {
//            resp = CONTROL.actualizar(Integer.parseInt(txtId.getText().trim()), txtNombre.getText().trim(),
//                    Double.parseDouble(txtPrecio.getText()), Integer.parseInt(txtStock.getText()), cat.getId(), prov.getRuc(), nombreAnterior);
//
//            if (resp.equals("OK")) {
//                this.mensajeOK("Actualizado correctamente");
//                this.limpiar();
//                this.listar();
//
//                tabGeneral.setEnabledAt(0, true);
//                tabGeneral.setEnabledAt(1, false);
//                tabGeneral.setSelectedIndex(0);
//            } else {
//                this.mensajeError(resp);
//            }
//        } else {
//            resp = CONTROL.insertar(Integer.parseInt(txtId.getText().trim()), txtNombre.getText().trim(), Double.parseDouble(txtPrecio.getText()),
//                    Integer.parseInt(txtStock.getText()), cat.getId(), prov.getRuc());
//
//            if (resp.equals("OK")) {
//                this.mensajeOK("Registrado correctamente");
//                this.limpiar();
//                this.listar();
//
//                tabGeneral.setEnabledAt(0, true);
//                tabGeneral.setEnabledAt(1, false);
//                tabGeneral.setSelectedIndex(0);
//            } else {
//                this.mensajeError(resp);
//            }
//        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
//        this.limpiar();
//        tabGeneral.setEnabledAt(0, true);
//        tabGeneral.setEnabledAt(1, false);
//        tabGeneral.setSelectedIndex(0);
//        accion = "Guardar";
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
//        String resp;
//        int fila = tabla.getSelectedRow();
//
//        if (fila >= 0) {
//            try {
//
//                resp = CONTROL.eliminar(Integer.parseInt(tabla.getValueAt(fila, 0).toString()));
//                if (resp.equals("OK")) {
//                    this.mensajeOK("Eliminado correctamente");
//                    this.listar();
//                }
//
//            } catch (NumberFormatException e) {
//                JOptionPane.showMessageDialog(this, "Error al eliminar el registro 1", "Error", JOptionPane.ERROR_MESSAGE);
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "La fila que intenta eliminar esta vacia", "Error", JOptionPane.QUESTION_MESSAGE);
//        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JComboBox<String> cboCategoria;
    public javax.swing.JComboBox<String> cboProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane tabGeneral;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPrecio;
    public javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
